// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © BritishBritishColumbian


//@version=5
// indicator('1.3.9.2: Simple market open follower', '1.3.9.2', false, format.inherit, 3)

strategy(
     "1.3.9.2: Historic extreme breaker",
     overlay=true, 
     margin_long=0, 
     margin_short=0, 
     default_qty_type=strategy.percent_of_equity, 
     default_qty_value=1,
     calc_on_every_tick=true)



//--------//
// Inputs //
//--------//

movingAveragePeriod = input.int(       
     group="Study parameters",
     title="candles to use for momentum calculation", 
     defval=16, 
     minval=1, 
     maxval=100)

requiredMomentum = input.float(       
     group="Trade Entry",
     title="momentum required for trade", 
     defval=0.0, 
     minval=0, 
     maxval=1)

trailingStopPercent = input.float(
     group="Trade Exit",
     title="percent price drop to halt trade", 
     defval=0.5, 
     minval=0, 
     maxval=10)

capPercent = input.float(
     group="Trade Exit",
     title="fraction or multiple of risk to exit on the positive side of the trade", 
     defval=0.3, 
     minval=0, 
     maxval=5.0)

purchaseThreshold = input.float(
     group="Trade Entry",
     title="price difference required past previous extreme before entering trade", 
     defval=0, 
     minval=0, 
     maxval=10)

requiredOvernightChangeMin = input.float(
     group="Previous Change",
     title="minimum percentage overnight change to allow trade", 
     minval=-100, 
     defval=0, 
     maxval=100)

requiredOvernightChangeMax = input.float(
     group="Previous Change",
     title="maximum percentage overnight change to allow trade", 
     minval=-100, 
     defval=0, 
     maxval=100)

useOutsideOvernightChange = input.bool(
     group="Previous Change",
     title="Use outside of overnight range",
     defval=true)

requiredIntradayChangeMin = input.float(
     group="Previous Change",
     title="minimum percentage intraday change to allow trade", 
     minval=-100, 
     defval=0, 
     maxval=100)

requiredIntradayChangeMax = input.float(
     group="Previous Change",
     title="maximum percentage intraday change to allow trade", 
     minval=-100, 
     defval=0, 
     maxval=100)

useOutsideIntradayChange = input.bool(
     group="Previous Change",
     title="Use outside of intraday range",
     defval=true)

requiredTotalChangeChanceMin = input.float(
     group="Previous Change",
     title="minimum total change chance to allow trade", 
     minval=0, 
     defval=0, 
     maxval=1)

requiredTotalChangeChanceMax = input.float(
     group="Previous Change",
     title="maximum  total change chance to allow trade", 
     minval=0, 
     defval=0.2, 
     maxval=1)

useOutsideTotalChangeChance = input.bool(
     group="Previous Change",
     title="Use outside of totalChangeChance",
     defval=false)


allowCalls = input.bool(
     group="Trades allowed",
     title="Allow calls",
     defval=true)

allowPuts = input.bool(
     group="Trades allowed",
     title="Allow puts",
     defval=true)

lastTradeHour = input.int(
     group="Day bounds",
     title="Last trade (hour)",
     defval=9,
     minval=0,
     maxval=24)

lastTradeMinute = input.int(
     group="Day bounds",
     title="Last trade (minute)",
     defval=30,
     minval=0,
     maxval=59)

debugPlotsEnabled = input.bool(
     group="Debug",
     title="Show debug plots",
     defval=false)



//-------------//
// Plot colors //
//-------------//

// Fixed colors
positiveColor = color.new(#51B561, 30)
positiveFadedColor = color.new(positiveColor, 70)
negativeColor = color.new(#FA4040, 50)
negativeFadedColor = color.new(negativeColor, 80)
buyColor = color.new(#7A00FA, 50)
debugColor = color.new(#FF7F00, 80)

// Customizable colors
tradeWarningColor =         input.color(#d0d0d0, 'Trade warning')
maximaDeltaColorInput =     input.color(#53A4F3, "Maxima delta")
minimaDeltaColorInput =     input.color(#825FC2, "Minima delta")
momentumColor =             input.color(#007FFF40, "Momentum")
overnightChangeColor =      input.color(color.rgb(71, 77, 255), "Overnight change")
intradayChangeColor =       input.color(color.rgb(255, 200, 0), "Intraday change")
totalChangeColor =          input.color(color.rgb(0, 180, 60), "Total change")
totalChangeChanceColor =    input.color(#00b43c2F, "Total change chance")



//-----------//
// Constants //
//-----------//

varip unset = -1.0
varip continuousTradeWarningRequired = 1.8



//------------------//
// Accessor backing //
//------------------//

varip prevDayExtremes = array.new_float(2, -1.0)
varip premarketExtremes = array.new_float(2, -1.0)
varip dayExtremes = array.new_float(2, -1.0)
varip extremaExtremes = array.new_float(2, -1.0)
varip tradeExtremes = array.new_float(2, -1.0)



//---------------//
// Trade results //
//---------------//

varip tradeStatus = array.new_bool(1, 0)
varip tradeOpenIndex = 0

varip tradeResults = array.new_float(9, 0)
varip buyIndex = 0
varip drawdownIndex = 1
varip gainIndex = 2
varip maxDailyDrawdownIndex = 3
varip maxDrawdownIndex = 4
varip totalGainIndex = 5
varip sellIndex = 6
varip numTradesTodayIndex = 7
varip lastTradeDirection = 8



//----------------//
// Global indices //
//----------------//

varip minIndex = 0
varip maxIndex = 1
varip latestMinMax = 1
varip buyBarCloseTime = 0


//---------//
// Signals //
//---------//

varip signals = array.new_float(3, 0)
varip directionIndex = 0
varip buySignalIndex = 1
varip sellSignalIndex = 2



//---------//
// Metrics //
//---------//

varip metrics = array.new_float(3, 0)
varip numTradesIndex = 0
varip numSuccessIndex = 1
varip numWarningsIndex = 2



//---------------------------------//
// Temp variables (reset each bar) //
//---------------------------------//

varip prevBarClose = 0
varip continuousTradeWarning = 0.0
tradeWarning = 0
trailingStop = close * trailingStopPercent / 100.0



//-----------//
// Accessors //
//-----------//


//---------//
// Signals //
//---------//

getBuySignal() => 
    array.get(signals, buySignalIndex)

setBuySignal(value) => 
    array.set(signals, buySignalIndex, value)

getSellSignal() => 
    array.get(signals, sellSignalIndex)

setSellSignal(value) => 
    array.set(signals, sellSignalIndex, value)
    if (value == -1)
        strategy.close_all()

getDirection() => 
    array.get(signals, directionIndex)

setDirection(value) => 
    array.set(signals, directionIndex, value)
    if (value == 1)
        strategy.entry("Call", strategy.long, 1) 
    else if (value == -1)
        strategy.entry("Put", strategy.short, 1)



//---------//
// Metrics //
//---------//

getNumTrades() => 
    array.get(metrics, numTradesIndex)

setNumTrades(trades) => 
    array.set(metrics, numTradesIndex, trades)

getSuccessTrades() => 
    array.get(metrics, numSuccessIndex)

setSuccessTrades(trades) => 
    array.set(metrics, numSuccessIndex, trades)

getWarnings() => 
    array.get(metrics, numWarningsIndex)

setWarnings(trades) => 
    array.set(metrics, numWarningsIndex, trades)



//---------------//
// Trade Results //
//---------------//

getDrawdown() =>
    array.get(tradeResults, drawdownIndex)

getMaxDailyDrawdown() =>
    array.get(tradeResults, maxDailyDrawdownIndex)

getMaxDrawdown() =>
    array.get(tradeResults, maxDrawdownIndex)

setMaxDrawdown(value) =>
    array.set(tradeResults, maxDrawdownIndex, value)

setDrawdown(value) =>
    array.set(tradeResults, drawdownIndex, value)
    if (value < array.get(tradeResults, maxDailyDrawdownIndex) and value > -100)
        array.set(tradeResults, maxDailyDrawdownIndex, value)

getBuyPrice() =>
    array.get(tradeResults, buyIndex)

setBuyPrice(value) =>
    array.set(tradeResults, buyIndex, value)

getSellPrice() =>
    array.get(tradeResults, sellIndex)

setSellPrice(value) =>
    array.set(tradeResults, sellIndex, value)

getNumTradesToday() =>
    array.get(tradeResults, numTradesTodayIndex)

setNumTradesToday(value) =>
    array.set(tradeResults, numTradesTodayIndex, value)

getTradeOpen() =>
    array.get(tradeStatus, tradeOpenIndex)

setTradeOpen(bool value) =>
    array.set(tradeStatus, tradeOpenIndex, value)
    setNumTradesToday(getNumTradesToday() + 1)

getLastTradeDirection() =>
    array.get(tradeResults, lastTradeDirection)

setLastTradeDirection(value) =>
    array.set(tradeResults, lastTradeDirection, value)

getGain() =>
    array.get(tradeResults, gainIndex)

setGain(value) =>
    array.set(tradeResults, gainIndex, value)

getTotalGain() =>
    array.get(tradeResults, totalGainIndex)

setTotalGain(value) =>
    array.set(tradeResults, totalGainIndex, value)
    if (value < getMaxDrawdown())
        setMaxDrawdown(value)



//--------------------//
// Premarket Extremes //
//--------------------//

getPremarketMin() =>
    array.get(premarketExtremes, minIndex)

setPremarketMin(value) =>
    array.set(premarketExtremes, minIndex, value)

getPremarketMax() =>
    array.get(premarketExtremes, maxIndex)

setPremarketMax(value) =>
    array.set(premarketExtremes, maxIndex, value)



//--------------//
// Day Extremes //
//--------------//

getDayMin() =>
    array.get(dayExtremes, minIndex)

setDayMin(value) =>
    array.set(dayExtremes, minIndex, value)

getDayMax() =>
    array.get(dayExtremes, maxIndex)

setDayMax(value) =>
    array.set(dayExtremes, maxIndex, value)



//-------------------------//
// Previous Day's Extremes //
//-------------------------//

getPrevDayMin() =>
    array.get(prevDayExtremes, minIndex)

setPrevDayMin(value) =>
    array.set(prevDayExtremes, minIndex, value)

getPrevDayMax() =>
    array.get(prevDayExtremes, maxIndex)

setPrevDayMax(value) =>
    array.set(prevDayExtremes, maxIndex, value)

shiftDayExtremesIfValid() =>
    if (getDayMin() >= 0)
        setPrevDayMin(getDayMin())

    if (getDayMax() >= 0)   
        setPrevDayMax(getDayMax())



//---------//
// Actions //
//---------//

endTrade(sellPrice) =>
    setTradeOpen(false)
    var actualGain = 0.0
    if (getDirection() > 0) 
        actualGain := sellPrice - getBuyPrice()
    else 
        actualGain := getBuyPrice() - sellPrice

    setSellSignal(-1)
    setDirection(0)

    setNumTrades(getNumTrades() + 1)

    
    if actualGain > 0.2
        setSuccessTrades(getSuccessTrades() + 1)

    setTotalGain(actualGain + getTotalGain())

    array.set(tradeExtremes, minIndex, -1.0)
    array.set(tradeExtremes, maxIndex, -1.0)
    setBuyPrice(unset)
    setSellPrice(sellPrice)

    setDrawdown(0)
    setGain(0)

resetEverything() =>
    setTradeOpen(false)
    setDayMin(-1.0)
    setDayMax(-1.0)
    array.set(tradeExtremes, minIndex, -1.0)
    array.set(tradeExtremes, maxIndex, -1.0)
    setBuyPrice(unset)
    setDrawdown(0)
    array.set(tradeResults, maxDailyDrawdownIndex, 0.0)
    setGain(0)
    setDirection(0)
    setNumTradesToday(0)
    setLastTradeDirection(0)



//--------------//
// Conditionals //
//--------------//

newBar() =>
    // TODO: This isn't accurate when using realtime data
    time_close("") > prevBarClose
    
outsideTradingHours() =>
    hour < 9 
     or (hour == 9 and minute < 30) 
     or hour > 15

validForExtremeCalculation() =>
    not na(time(timeframe.period, "0930-1600"))

goodToTrade() => 
    dayStartHour = 9
    dayStartMinute = 30
    startString = str.tostring(dayStartHour, "00") + str.tostring(dayStartMinute, "00")
    endString = str.tostring(lastTradeHour, "00") + str.tostring(lastTradeMinute, "00")

    not na(time(timeframe.period, startString + "-" + endString))

isPremarket() =>
    not na(time(timeframe.period, "0000-0930"))

isPostmarket() =>
    not na(time(timeframe.period, "1600-2359"))

//------------------------------------------//
// Calculate overnight and intraday changes //
//------------------------------------------//

varip float prevDayClose = na
varip float currentDayOpen = na
varip bool newDay = false
varip int prevDay = 0

tempPrevDayClose = request.security(syminfo.tickerid, "1D", close)  // Changes with current price

newDay := dayofmonth(time) != prevDay and not outsideTradingHours()

if newDay 
    prevDay := dayofmonth(time)
    prevDayClose := tempPrevDayClose
    currentDayOpen := open

// This (low) needs to be changed to not always use low 
//   - there should be a range for each bar, 
//     which is taken into account with other calculations
intradayChange = (low / currentDayOpen - 1) * 100
overnightChange = (currentDayOpen / prevDayClose - 1) * 100
totalChange = overnightChange + intradayChange

// Approximate the CDF of the standard normal distribution
// Using the error function (erf) approximation for the CDF
erf(totalChange) =>
    sign = totalChange < 0 ? -1 : 1
    t = 1 / (1 + 0.5 * math.abs(totalChange))
    tau = t * math.exp(-totalChange * totalChange - 1.26551223 + t * (1.00002368 + t * (0.37409196 + t * (0.09678418 + t * (-0.18628806 + t * (0.27886807 + t * (-1.13520398 + t * (1.48851587 + t * (-0.82215223 + t * 0.17087277)))))))))
    1 - sign * tau

totalChangeChance() =>
    // Normal Distribution stats for S&P
    mean = 0.0325
    stdDev = 0.9650
    e = 2.71828

    // Calculate the Z-score
    z = (totalChange - mean) / stdDev

    math.abs(0.5 * (1 + erf(z / math.sqrt(2))) - 1)

overnightChangeIsValid() => 
    if useOutsideOvernightChange 
        overnightChange > requiredOvernightChangeMax or overnightChange <= requiredOvernightChangeMin
    else 
        overnightChange < requiredOvernightChangeMax and overnightChange >= requiredOvernightChangeMin

intradayChangeIsValid() => 
    if useOutsideIntradayChange 
        intradayChange > requiredIntradayChangeMax or intradayChange <= requiredIntradayChangeMin
    else 
        intradayChange < requiredIntradayChangeMax and intradayChange >= requiredIntradayChangeMin

totalChangeChanceIsValid() => 
    chance = totalChangeChance()

    if useOutsideTotalChangeChance 
        chance > requiredTotalChangeChanceMax or chance < requiredTotalChangeChanceMin
    else 
        chance < requiredTotalChangeChanceMax and chance > requiredTotalChangeChanceMin

outsideExtremes(int direction) =>
    if (direction < 0)
        low < getPremarketMin() - purchaseThreshold //and close < getPrevDayMin()

    else if (direction > 0)
        high > getPremarketMax() + purchaseThreshold//and close > getPrevDayMax()

tradeValid(int direction, float maTrend) =>
    bool momentumValid = false
    if (direction < 0)
        momentumValid := maTrend * 100 <= -requiredMomentum
    else if (direction > 0)
        momentumValid := maTrend * 100 >= requiredMomentum
    
    momentumValid
     and outsideExtremes(direction)
     and intradayChangeIsValid()
     and totalChangeChanceIsValid()
    //  and totalChange < 0
     and (getNumTradesToday() == 0)    // Prevents multiple trades
    //  and goodToTrade()

openTrade(int direction, priceWhenValid) =>
    setTradeOpen(true)
    buyPrice = priceWhenValid
    setBuyPrice(buyPrice)    // This is being called during a trade
    setDirection(direction)
    setLastTradeDirection(direction)
    setGain(0)
    setDrawdown(0)
    setBuySignal(1)


//----------------------------//
// Temp variables from arrays //
//----------------------------//

dayMin = getDayMin()
dayMax = getDayMax()

tradeMin = array.get(tradeExtremes, minIndex)
tradeMax = array.get(tradeExtremes, maxIndex)

movingAverage = ta.sma(close[1], movingAveragePeriod)
maTrend = movingAverage / movingAverage[1] - 1



//---------------------//
// Tidy up for new bar //
//---------------------//

if (newBar())
    setBuySignal(0)
    setSellSignal(0)



//-------------------//
// Start calculating //
//-------------------//

if (isPremarket()) 
    if (low < getPremarketMin() or getPremarketMin() < 0)
        setPremarketMin(low)

    if (high > getPremarketMax() or getPremarketMax() < 0)
        setPremarketMax(high)

if (isPostmarket()) 
    setPremarketMin(-1.0)
    setPremarketMax(-1.0)

if (outsideTradingHours())
    shiftDayExtremesIfValid()

    resetEverything()
    continuousTradeWarning := 0.0

else
    // Inside trading hours; game on!
    // TODO: Define exactly what each of these conditionals represents...

    if (low[1] < dayMin or dayMin < 0)
        setDayMin(low[1])
        ignore = true   // Hack to prevent the array assignment scrwwing with the conditionals

    if (high[1] > dayMax or dayMax < 0)
        setDayMax(high[1])
        ignore = true   // Hack to prevent the array assignment scrwwing with the conditionals



    //--------------------------//
    // Continuous trade warning //
    //--------------------------//

    varip prevContinuousTradeWarning = 0.0
    varip extremeThreshold = 0.35
    varip requiredMomentumFraction = 0.7 

    momentum = (maTrend * 100)
    continuousTradeWarning := 0

    if (overnightChangeIsValid() and intradayChangeIsValid() and ((momentum > 0 and allowCalls) or (momentum < 0 and allowPuts)))
        continuousTradeWarning += 1

    if (momentum > 0 and allowCalls)
        distanceToMax = high - dayMax   // +ve if higher than day max
        if (momentum > requiredMomentum * requiredMomentumFraction and distanceToMax > -extremeThreshold)
            continuousTradeWarning += 1


    else if (momentum < 0 and allowPuts)
        distanceToMin = dayMin - low    // +ve if lower than day min 
        if (momentum < -requiredMomentum * requiredMomentumFraction and distanceToMin > -extremeThreshold)
            continuousTradeWarning += 1

    else 
        continuousTradeWarning := 0

    if (prevContinuousTradeWarning < continuousTradeWarning and not getTradeOpen() and overnightChangeIsValid())
        setWarnings(getWarnings() + 1)
        tradeWarning := int(continuousTradeWarning)

    if (newDay and overnightChangeIsValid() == false)
        continuousTradeWarning := -1
        tradeWarning := int(continuousTradeWarning)


    prevContinuousTradeWarning := continuousTradeWarning



    //-------------//
    // Open trade? //
    //-------------//

    

    if (allowPuts and tradeValid(-1, maTrend))
        // Sufficient to buy put

        if (getTradeOpen() == false)// or getDirection() > 0)

            // New low and buy price hasn't been set (or direction has changed); set buy price
            openTrade(-1, getPremarketMin() - purchaseThreshold)
            buyBarCloseTime := time_close("")


    else if (allowCalls and tradeValid(1, maTrend))
        // Sufficient to buy call

        if (getTradeOpen() == false)// or getDirection() < 0)

            // New high and buy price hasn't been set (or direction has changed); set buy price
            openTrade(1, getPremarketMax() + purchaseThreshold)
            buyBarCloseTime := time_close("")

    if (getTradeOpen())

        // Trade is open; track drawdown and gain

        if (getGain() > capPercent * trailingStop)
            setNumTradesToday(getNumTrades() + 1)
            endPrice = getBuyPrice() + getDirection() * capPercent * trailingStop
            endTrade(endPrice)

        else if (getDirection() < 0)  // Heading down
                
            // TODO: Should the drawdown be ignored on the first candle? Perhaps, since the strategy takes the extreme from that bar
            if (time_close("") > buyBarCloseTime)   // Avoid drawdown on the first candle
                gainAtOpen = getBuyPrice() - open
                setGain(gainAtOpen)
                drawdownAtOpen = tradeMin - open            // -ve if open is above previous min
                setDrawdown(math.min(0, drawdownAtOpen))   // saved drawdown is always -ve
                if (drawdownAtOpen < -trailingStop)          // this is needed due to sequential scope of functions
                    endTrade(open)
                else
                    // Find the best case exit within the bar (i.e. as soon as the trailing stop is hit)
                    bestCasePriceInsideBar = high
                    if (bestCasePriceInsideBar > tradeMin + trailingStop)
                        bestCasePriceInsideBar := tradeMin + trailingStop
                    else
                        bestCasePriceInsideBar := low

                    localGain = getBuyPrice() - bestCasePriceInsideBar
                    setGain(localGain)
                    localDrawdown = tradeMin - high
                    setDrawdown(math.min(0, localDrawdown))
                    if (localDrawdown < -trailingStop) // this is needed due to sequential scope of functions
                        endTrade(bestCasePriceInsideBar)

        
        else if (getDirection() > 0)  // Heading up
                
            if (time_close("") > buyBarCloseTime)   // Avoid drawdown on the first candle
                gainAtOpen = open - getBuyPrice()
                setGain(gainAtOpen)
                drawdownAtOpen = tradeMax - open            // -ve if open is above previous max
                setDrawdown(math.min(0, -drawdownAtOpen))   // saved drawdown is always -ve
                if (drawdownAtOpen > trailingStop)          // this is needed due to sequential scope of functions
                    endTrade(open)
                else
                    // Find the best case exit within the bar (i.e. as soon as the trailing stop is hit)
                    bestCasePriceInsideBar = low
                    if (bestCasePriceInsideBar < tradeMax - trailingStop)
                        bestCasePriceInsideBar := tradeMax - trailingStop
                    else 
                        bestCasePriceInsideBar := high

                    localGain = bestCasePriceInsideBar - getBuyPrice()
                    setGain(localGain)
                    localDrawdown = tradeMax - low 
                    setDrawdown(math.min(0, -localDrawdown))
                    if (localDrawdown > trailingStop)       // this is needed due to sequential scope of functions
                        endTrade(bestCasePriceInsideBar)

        if (getGain() > capPercent * trailingStop)
            setNumTradesToday(getNumTrades() + 1)
            endPrice = getBuyPrice() + getDirection() * capPercent * trailingStop
            endTrade(endPrice)
          
        // Set trade min/max
        // TODO: I think there's an issue here.. The trade min/max should be set based on direction, no?
        if (tradeMin < 0)
            array.set(tradeExtremes, minIndex, math.min(low, getBuyPrice()))
        else
            array.set(tradeExtremes, minIndex, math.min(low, tradeMin, getBuyPrice()))

        if (tradeMax < 0)
            array.set(tradeExtremes, maxIndex, math.max(high, getBuyPrice()))
        else
            array.set(tradeExtremes, maxIndex, math.max(high, tradeMax, getBuyPrice()))

        ingoreReturnType = true


//-------//
// Plots //
//-------//

var dontDisplayInStatusBar = display.all - display.status_line
var dontDisplayInChart = display.all - display.pane
var displayIfDebugEnabled = debugPlotsEnabled ? display.all : display.none

// Current concern
plot(overnightChange, title="Overnight change", style=plot.style_line, color = overnightChangeColor, display = displayIfDebugEnabled)
plot(intradayChange, title="Intraday change", style=plot.style_line, color = intradayChangeColor, display = displayIfDebugEnabled)
plot(totalChangeChance(), title="Total change chance", style=plot.style_area, color = totalChangeChanceColor, display = display.all)
plot(totalChangeChanceIsValid() ? 1 : 0, title="Total change chance valid", style=plot.style_area, color = totalChangeChanceColor, display = dontDisplayInStatusBar)

// Gain / Drawdown
plot(getDrawdown(), title="Drawdown", style=plot.style_columns, color = negativeFadedColor, display = displayIfDebugEnabled)
plot(getGain(), title="Gain", style=plot.style_columns, color = positiveFadedColor)

// Debug plots
warningColor = color.new(buyColor, 80)
plot(tradeWarning * 2, title="Trade warning", style=plot.style_columns, color = tradeWarning < 0 ? negativeColor : warningColor, display = dontDisplayInStatusBar)
plot(getDirection(), title="Direction", style=plot.style_line, color = buyColor, display = displayIfDebugEnabled)
plot(getBuySignal(), title="Buy signal", style=plot.style_columns, color = buyColor, display = dontDisplayInStatusBar)
plot(getSellSignal(), title="Sell signal", style=plot.style_columns, color = buyColor, display = dontDisplayInStatusBar)
plot(getMaxDailyDrawdown(), title="Max Drawdown For Day", style=plot.style_line, color = negativeColor, display = displayIfDebugEnabled)
plot(maTrend * 100 / requiredMomentum, title="Momentum %", style=plot.style_area, color = momentumColor, linewidth=2)
plot(getBuyPrice(), title="Buy Price", style=plot.style_line, color = debugColor, display = displayIfDebugEnabled)
plot(getSellPrice(), title="Sell Price", style=plot.style_line, color = debugColor, display = displayIfDebugEnabled)
plot((goodToTrade() ? 1 : 0), title="Good to trade", style=plot.style_columns, color = debugColor, display = displayIfDebugEnabled)
plot(getDayMin(), title="Day Min", style=plot.style_line, color = debugColor, display = displayIfDebugEnabled)
plot(getDayMax(), title="Day Max", style=plot.style_line, color = debugColor, display = displayIfDebugEnabled)
plot(prevDayClose, title="Previous Day's Close", style=plot.style_line, color = debugColor, display = displayIfDebugEnabled)

plot(getPrevDayMin(), title="Previous Day Min", style=plot.style_line, color = debugColor, display = dontDisplayInChart)
plot(getPrevDayMax(), title="Previous Day Max", style=plot.style_line, color = debugColor, display = dontDisplayInChart)
plot(getPremarketMin(), title="Premarket Min", style=plot.style_line, color = debugColor, display = dontDisplayInChart)
plot(getPremarketMax(), title="Premarket Max", style=plot.style_line, color = debugColor, display = dontDisplayInChart)

// Metric plots
plot(getTotalGain(), title="Total Gain", style=plot.style_line, color = positiveColor, display = dontDisplayInChart)
plot(getNumTradesToday(), title="Trades", style=plot.style_line, color = debugColor)
plot(getSuccessTrades() / getNumTrades(), title="Success Ratio", style=plot.style_line, color = debugColor)

// Track the close of this bar so we can determine if the next run is a new bar    
prevBarClose := time_close("")


//------------//
// End trade? //
//------------//

// Only end the trade after everything has been plotted

if (getTradeOpen()) 
    if (getDrawdown() < -trailingStop)
        endTrade(close)
        ingoreReturnTypeAgain = true

    else if (hour == 15 and minute >= 45)
        endTrade(close)
        ingoreReturnTypeAgain = true